export const GET_POKEMONS = 'GET_POKEMONS';
export const GET_POKEMONS_SUCCESS = 'GET_POKEMONS_SUCCESS';
export const GET_POKEMONS_FAILURE = 'GET_POKEMONS_FAILURE';

export const SEARCH_POKEMON = 'SEARCH_POKEMON';
export const SEARCH_POKEMON_SUCCESS = 'SEARCH_POKEMON_SUCCESS';
export const SEARCH_POKEMON_FAILURE = 'SEARCH_POKEMON_FAILURE';

export const GET_POKEMON = 'GET_POKEMON';
export const CLEAR_POKEMON = 'CLEAR_POKEMON';

export const GET_DESCRIPTION = 'GET_DESCRIPTION';
export const GET_DESCRIPTION_SUCCESS = 'GET_DESCRIPTION_SUCCESS';
export const GET_DESCRIPTION_FAILURE = 'GET_DESCRIPTION_FAILURE';

export const GET_ABILITIES_DESCRIPTIONS = 'GET_ABILITIES_DESCRIPTIONS';
export const GET_ABILITIES_DESCRIPTIONS_SUCCESS = 'GET_ABILITIES_DESCRIPTIONS_SUCCESS';
export const GET_ABILITIES_DESCRIPTIONS_FAILURE = 'GET_ABILITIES_DESCRIPTIONS_FAILURE';
export const CLEAR_ABILITIES_DESCRIPTIONS = 'CLEAR_ABILITIES_DESCRIPTIONS';

export const GET_EVOLUTIONS = 'GET_EVOLUTIONS';
export const GET_EVOLUTIONS_SUCCESS = 'GET_EVOLUTIONS_SUCCESS';
export const GET_EVOLUTIONS_FAILURE = 'GET_EVOLUTIONS_FAILURE';

export const SET_LOCAL_STORAGE = 'SET_LOCAL_STORAGE';
export const GET_LOCAL_STORAGE = 'GET_LOCAL_STORAGE';
export const DELETE_LOCAL_STORAGE = 'DELETE_LOCAL_STORAGE';

export const GET_POKEMONS_RECOMMENDED = 'GET_POKEMONS_RECOMMENDED';
export const GET_RECOMMENDED_SUCCESS = 'GET_RECOMMENDED_SUCCESS';
export const GET_RECOMMENDED_FAILURE = 'GET_RECOMMENDED_FAILURE';